# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI5.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(245, 340)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnShowModelStructure = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowModelStructure.setEnabled(True)
        self.btnShowModelStructure.setGeometry(QtCore.QRect(35, 30, 180, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShowModelStructure.sizePolicy().hasHeightForWidth())
        self.btnShowModelStructure.setSizePolicy(sizePolicy)
        self.btnShowModelStructure.setObjectName("btnShowModelStructure")
        self.btnShowTensorBoard = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowTensorBoard.setGeometry(QtCore.QRect(35, 80, 180, 25))
        self.btnShowTensorBoard.setObjectName("btnShowTensorBoard")
        self.teSelect = QtWidgets.QTextEdit(self.centralwidget)
        self.teSelect.setGeometry(QtCore.QRect(35, 180, 180, 30))
        self.teSelect.setObjectName("teSelect")
        self.btnTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnTest.setGeometry(QtCore.QRect(35, 130, 180, 25))
        self.btnTest.setObjectName("btnTest")
        self.btnDataAugmentation = QtWidgets.QPushButton(self.centralwidget)
        self.btnDataAugmentation.setGeometry(QtCore.QRect(35, 240, 180, 25))
        self.btnDataAugmentation.setObjectName("btnDataAugmentation")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 245, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2021 Opencvdl Hw2 5."))
        self.btnShowModelStructure.setText(_translate("MainWindow", "1. Show Model Structure"))
        self.btnShowTensorBoard.setText(_translate("MainWindow", "2. Show TensorBoard"))
        self.teSelect.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnTest.setText(_translate("MainWindow", "3. Test"))
        self.btnDataAugmentation.setText(_translate("MainWindow", "4. Data Augmentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
